openapi: "3.0.2"
info:
  title: Block Explorer Data API for L1->L2 Transactions Extension
  description: >
    Extension of the Reference API specification for L2 blockchain explorers.
    This extension inherits from the core specification.
  version: "1.0"

paths:
  # This path overrides the inherited path
  /transactions/{txHash}:
    get:
      summary: Get core details of a L2 transaction.
      parameters:
        - name: txHash
          in: path
          required: true
          description: Transaction hash.
          schema:
            type: string
            example: "0xd49ef9608fcc840cae432066b1815872539c1bdfdd505bea865dc560bf410c90"
      responses:
        "404":
          description: A transaction with the given hash was not found.
        "200":
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "1_4_1_core.yml#/components/schemas/TransactionDetail"
                  - $ref: "#/components/schemas/L1L2TransactionDetail"

  # This path overrides the inherited path
  /transactions:
    get:
      summary: Get a list of L2 transactions.
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set.
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    description: A list of L2 transactions.
                    type: array
                    items:
                      $ref: "#/components/schemas/TransactionListElement"
                  paginationContext:
                    $ref: "1_4_1_core.yml#/components/schemas/PaginationContext"

components:
  schemas:
    L1L2TransactionDetail:
      allOf:
        - $ref: "1_4_1_core.yml#/components/schemas/TransactionDetail"
        - type: object
          properties:
            l1Origin:
              type: string
              description: The hash of the originating L1 transactions.
    TransactionListElement:
      allOf:
        - $ref: "1_4_1_core.yml#/components/schemas/TransactionListElement"
        - type: object
          properties:
            isL1L2:
              type: boolean
              description: True if this is an L1->L2 transaction.
