openapi: "3.0.2"
info:
  title: Block Explorer Data API for Event Logs Extension
  description: >
    Extension of the Reference API specification for L2 blockchain explorers.
    This extension inherits from the core specification.
  version: "1.0"

paths:
  /transactions/{txHash}/events:
    get:
      summary: Get event log details of a L2 transaction.
      parameters:
        - name: txHash
          in: path
          required: true
          description: Transaction hash.
          schema:
            type: string
            example: "0xd49ef9608fcc840cae432066b1815872539c1bdfdd505bea865dc560bf410c90"
      responses:
        "404":
          description: A transaction with the given hash was not found.
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventLogList"

components:
  schemas:
    EventLogList:
      description: A list of event logs.
      type: array
      items:
        $ref: "#/components/schemas/EventLogDetail"
    EventLogDetail:
      description: Details of an event log.
      type: object
      properties:
        id:
          type: string
          description: An index or identifier that uniquely identifies the event in the transaction.
        address:
          $ref: "1_4_1_core.yml#/components/schemas/Address"
        signature:
          type: string
          description: The combination of the event name and the types of parameters it contains.
          example: Transfer(address,address,uint256)
        topics:
          type: array
          description: >
            A log topic is a 32-byte word used to describe the inner workings of an event.
            A log object describing an event can have up to four topics.
            The first topic corresponds to the keccak256 hash of the event signature (except for anonymous events).
            The remaining topics are used for the values of indexed parameters in the event.
          items:
            type: string
            example: "0x3d0ce9bfc3ed7d6862dbb28b2dea94561fe714a1b4d019aa8af39730d1ad7c3d"
        value:
          type: string
          description: The hexidecimal encoded value of the event parameters.
          example: "0x000000000000000000000000000000000000000000000000000000f62a1738a5"
        data:
          type: array
          items:
            type: object
            properties:
              name:
                description: The name of the event parameter.
                type: string
                example: "gasUsed"
              value:
                description: The value of the event parameter, decoded to be human-readable based on the type.
                type: string
                example: "150288"
              type:
                description: The type of the event parameter (e.g. address, uint256, bytes32, bool).
                type: string
                example: "uint256"
          nullable: true
