openapi: "3.0.2"
info:
  title: Block Explorer Data API for Ethereum Account Extension
  description: >
    Extension of the Reference API specification for L2 blockchain explorers.
    This extension inherits from the core specification.
  version: "1.0"

paths:
  /accounts/{address}:
    get:
      summary: Get core details of a L2 account.
      parameters:
        - name: address
          in: path
          required: true
          description: The unique identifier of an Ethereum account (the account address).
          schema:
            type: string
            example: "0x7681ed0bbbcd36b55d98d911f97ccc0ad2eb2174"
      responses:
        "404":
          description: An account with the given address was not found.
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDetail"

  /accounts/{address}/transactions:
    get:
      summary: Get a list of L2 transactions sent to or from this account.
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set.
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return.
        - in: query
          name: filter
          description: Optionally filter only L2 transactions where this account is the sender or receiver.
          schema:
            type: string
            enum:
              - sender
              - receiver
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "1_4_1_core.yml#/components/schemas/TransactionList"
                  paginationContext:
                    $ref: "1_4_1_core.yml#/components/schemas/PaginationContext"

components:
  schemas:
    AccountDetail:
      description: Core details about a L2 account.
      type: object
      properties:
        address:
          type: string
          example: "0x7681ed0bbbcd36b55d98d911f97ccc0ad2eb2174"
          description: The unique identifier of an Ethereum account (the account address).
        balance:
          type: string
          example: "12345"
          description: >
            Balance of the account in the chain's native token (e.g. ETH).
            This value is a uint256 in decimal form presented as a string.
