openapi: "3.0.2"
info:
  title: Block Explorer Data API for Optimistic Rollup Extension
  description: >
    Extension of the Reference API specification for L2 blockchain explorers.
    This extension inherits from the core specification.
  version: "1.0"

paths:
  # This path overrides the inherited path
  /blocks/{blockId}:
    get:
      summary: Get core details of a L2 block.
      parameters:
        - name: blockId
          in: path
          required: true
          description: The unique identifier of a block (e.g. the block hash).
          schema:
            type: string
            example: "0x079dba31b02aad5eb8c617400bbe77aaa5b86f12a89b559916a7577419827ed0"
      responses:
        "404":
          description: A block with the given identifier was not found.
        "200":
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "1_4_1_core.yml#/components/schemas/BlockDetail"
                  - $ref: "#/components/schemas/ChallengedBlockDetail"

  # This path overrides the inherited path
  /blocks:
    get:
      summary: Get a list of L2 blocks.
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set.
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    description: A list of L2 blocks.
                    type: array
                    items:
                      $ref: "#/components/schemas/BlockListElement"
                  paginationContext:
                    $ref: "1_4_1_core.yml#/components/schemas/PaginationContext"

components:
  schemas:
    ChallengedBlockDetail:
      allOf:
        - $ref: "1_4_1_core.yml#/components/schemas/BlockDetail"
        - $ref: "#/components/schemas/ChallengeStatus"
        - type: object
          properties:
            challengeTransaction:
              type: string
              description: The L1 transaction hash of a challenge.
    BlockListElement:
      allOf:
        - $ref: "1_4_1_core.yml#/components/schemas/BlockListElement"
        - $ref: "#/components/schemas/ChallengeStatus"
    ChallengeStatus:
      type: object
      properties:
        challengeStatus:
          type: string
          enum:
            - "Valid"
            - "Invalid"
            - "Pending"
          description: The status of a challenge.
          nullable: true
