openapi: "3.0.2"
info:
  title: Block Explorer Data API for Block Batch Extension
  description: >
    Extension of the Reference API specification for L2 blockchain explorers.
    This extension inherits from the core specification.
  version: "1.0"

paths:
  # This path overrides the inherited path
  /blocks/{blockId}:
    get:
      summary: Get core details of a L2 block.
      parameters:
        - name: blockId
          in: path
          required: true
          description: The unique identifier of a block (e.g. the block hash).
          schema:
            type: string
            example: "0x079dba31b02aad5eb8c617400bbe77aaa5b86f12a89b559916a7577419827ed0"
      responses:
        "404":
          description: A block with the given identifier was not found.
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlockDetail"

  /batches/{batchId}:
    get:
      summary: Get core details of a L2 block batch.
      parameters:
        - name: batchId
          in: path
          required: true
          description: The unique identifier of a L2 block batch (e.g. the block batch hash).
          schema:
            type: string
            example: "0x079dba31b02aad5eb8c617400bbe77aaa5b86f12a89b559916a7577419827ed0"
      responses:
        "404":
          description: A block batch with the given identifier was not found.
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchDetail"

  /batches:
    get:
      summary: Get a list of L2 block batches.
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set.
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/BatchList"
                  paginationContext:
                    $ref: "1_4_1_core.yml#/components/schemas/PaginationContext"

components:
  schemas:
    BatchDetail:
      description: Core details about an L2 block batch.
      type: object
      properties:
        id:
          type: string
          example: "0xeb016c292316e3af7f1c5184524b585a035d7ebeabddf52a1548fd376a77908a"
          description: The unique identifier of the L2 block batch (e.g. the block batch hash).
        status:
          type: string
          description: The status of this block batch with respect to the state of the chain. Possible values are chain-dependant.
        blocks:
          description: A list of L2 blocks included in this block batch.
          $ref: "1_4_1_core.yml#/components/schemas/BlockList"
    BatchList:
      description: A list of L2 block batches.
      type: array
      items:
        $ref: "#/components/schemas/BatchListElement"
    BatchListElement:
      description: Information about a L2 block batch to be displayed in a list.
      type: object
      properties:
        id:
          type: string
          example: "0xeb016c292316e3af7f1c5184524b585a035d7ebeabddf52a1548fd376a77908a"
          description: The unique identifier of the L2 block batch (e.g. the block batch hash).
    BlockDetail:
      allOf:
        - $ref: "1_4_1_core.yml#/components/schemas/BlockDetail"
        - type: object
          properties:
            batchId:
              type: string
              description: The unique identifier of the batch to which this block belongs (if applicable)
              nullable: true
